### ISSUE TITLE
bug:#对应字段名称#无法生成classname 前缀

### ISSUE THREAD

**Issue by bulolo** [taofed/imgcook#13]
5. 【可选】模块语义增强【前端注意】
在即将导出的模块根元素的文件夹名字上加上“#对应字段名称#”，此字段名称将作为生成代码 classname 前缀，当前端想要强制控制模块 classname 前缀时使用。

![image](https://user-images.githubusercontent.com/10026498/52128454-f844e200-266f-11e9-86e9-7de0b943dfdd.png)
![image](https://user-images.githubusercontent.com/10026498/52128468-ff6bf000-266f-11e9-9f2f-5126eb3b2b36.png)

**Comment by Ahkari** [comment]
这个确实是我们遗漏的一个问题。

我们之前只允许增加电商领域相关的词，现在可以考虑放开限制了。

**Comment by Ahkari** [comment]
类名前缀的限制已放开，此讨论关闭。
