### ISSUE TITLE
什么时候支持React Native？

### ISSUE THREAD

**Issue by johnnypenggg** [taofed/imgcook#15]
* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by sccgithub** [comment]
因为React Native的场景不是特别多，官方的DSL短期内不会添加React Native，不过DSL定制功能即将开放，到时候可以自己定制React Native的DSL

**Comment by Ahkari** [comment]
现在官方已经支持了自定义dsl的开发，可以生成满足自己诉求的代码。
https://imgcook.taobao.org/docs?slug=dsl-dev

您对生成RN代码有强诉求的话可以自己开发一个DSL，我们审核通过就可以让全平台用户使用了。
