### ISSUE TITLE
error: Cannot read property 'platform' of undefined

### ISSUE THREAD

**Issue by ashuiweb** [taofed/imgcook#16]
ps导出报错
error: Cannot read property 'platform' of undefined

**Comment by guangshao** [comment]
ps 2019 同样出现问题

**Comment by jerrytang67** [comment]
同样错误 ps 2019 cc

**Comment by haojiab** [comment]
同2019 cc报错

**Comment by jerrytang67** [comment]
win平台下运行方案，删除IMGCOOK插件目录node_modules文件夹。在当前目录运行命令行
