### ISSUE TITLE
首页单击“下载Sketch版插件”无法下载，页面自动关闭？？？

### ISSUE THREAD

**Issue by MickeyMouse-lh** [taofed/imgcook#17]
* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by MickeyMouse-lh** [comment]
chrome浏览器，版本 73.0.3683.86（正式版本） （64 位）

**Comment by 761647716** [comment]
> chrome浏览器，版本 73.0.3683.86（正式版本） （64 位）
我们使用同样版本的Chrome浏览器尝试复现这个问题，但是首页下载Sketch版插件并未出错呢，你这边是否能够提供更为详细的描述，便于我们进一步定位问题

**Comment by MickeyMouse-lh** [comment]
我这边无法复现这个问题，所以不能提供有效的case
