### ISSUE TITLE
安装ps插件不成功

### ISSUE THREAD

**Issue by wangli8095** [taofed/imgcook#20]
1、我是windows系统，在点击imgcook.photoshop_1.0.1.exe以后，弹出了一个运行的窗口，点击运行以后，会出现一个有I agree的窗口，点击I agree以后，会出现一个命令行窗口，但是命令行窗口过一会儿就会显示'failed to install status=-403'。
然后打开ps的window的Extensions，并没有找到imgcook插件。
我尝试解压 imgcook.photoshop.zip 文件，但是我的电脑根本找不到这个目录C:/Program Files (x86)/Common Files/Adobe/CEP/extensions/

**Comment by Tinple** [comment]
可以尝试下手动安装，如果你的 PS 版本是 CC 2017或者以上，应该是存在这个目录的

`C:/Program Files (x86)/Common Files/Adobe/CEP/extensions/`

**Comment by gyz418** [comment]
@wangli8095 pscc 2018 绿色版用不了吗？我解压imgcook.photoshop.zip放到指定的目录`C:/Program Files (x86)/Common Files/Adobe/CEP/extensions/`, 重新打开ps，该目录被清空了。一定要使用完整版？

**Comment by Tinple** [comment]
> @wangli8095 pscc 2018 绿色版用不了吗？我解压imgcook.photoshop.zip放到指定的目录`C:/Program Files (x86)/Common Files/Adobe/CEP/extensions/`, 重新打开ps，该目录被清空了。一定要使用完整版？

建议使用官方版本，一般插件目录是不会被自动清空的
