### ISSUE TITLE
用官方demo试了下有问题

### ISSUE THREAD

**Issue by tibic** [taofed/imgcook#21]
![image](https://user-images.githubusercontent.com/6113239/58695221-65227b80-83c7-11e9-911a-c912d300eb71.png)

![image](https://user-images.githubusercontent.com/6113239/58695122-2db3cf00-83c7-11e9-884f-5ace024af8c4.png)

**Comment by Ahkari** [comment]
感谢您的反馈：
第一个问题我们排查到了，您稍后更新下就好了呢。
第二个问题看起来是用了我们的代码后，在实际环境下跑出来的结果不符合预期？
能提供下您使用的dsl和环境信息吗？

**Comment by Ahkari** [comment]
问题已修复，关闭此issue。
问题一：
https://github.com/imgcook/imgcook-cli/commit/ac2a57b7f8e7a0abcb716bb7b3466eebb1331043
问题二：
https://github.com/imgcook-dsl/h5-standard/commit/c7ff4df8762195975faf6c2f6a4fdd668c767a2d
