### ISSUE TITLE
安装好了，点击插件后打开直接空白

### ISSUE THREAD

**Issue by blockmood** [taofed/imgcook#25]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, such as the following:

**Expected behavior**

**Screenshots**

*If you use sketch(Please complete the following information):*
 - PluginVersion: imgcook plugin version [e.g. 1.7.1]
 - sketchVersion: sketch version [e.g. 55.1]
 - sketchFile: problematic sketch file,compressed into zip

**Additional context**

**Comment by utkobe** [comment]
@blockmood  你好，请问您是导出成功后赚到edit页面空白吗

**Comment by blockmood** [comment]
@utkobe  第一次直接安装好之后，点插件-imgbook 弹出来就是一个空白

**Comment by Tinple** [comment]
可能是签署问题，可以看下 readme 里的签署解决方案

https://imgcook.taobao.org/docs#1ea91bf7

**Comment by blockmood** [comment]
@Tinple   好的 感谢 我去看看。

**Comment by zhangzhaoyong** [comment]
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令“转换为智能对象”当前不可用。

**Comment by Tinple** [comment]
> error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令“转换为智能对象”当前不可用。

这个是智能对象被锁定了的原因，可以先手动对 PS 里面的智能对象图层解锁来解决，我们本周会发布新版本修复这个问题。
