### ISSUE TITLE
margin: 'auto' 导出值为 NaNpx

### ISSUE THREAD

**Issue by taixw2** [taofed/imgcook#26]
**Describe the bug**
margin: 'auto' 导出值为 NaNpx

**Screenshots**
![image](https://user-images.githubusercontent.com/12482817/62419746-6d927d80-b6ba-11e9-92d9-7c5af595fe5c.png)

*If you use sketch(Please complete the following information):*
 - PluginVersion: imgcook:v1.0.7
 - photoshop: v19.1.2

**Additional context**

**Comment by Ahkari** [comment]
谢谢您的反馈。问题已修复，支持以下css数值。
['auto', 'inherit', 'initial', 'unset' ]
