### ISSUE TITLE
error: Unrecognized token '<'

### ISSUE THREAD

**Issue by rocketlyz** [taofed/imgcook#27]
**Describe the bug**
The website did't gave any response when I clicked '</>按钮' button to generated react code, and, if you have opened chrome's console panel, you would see error " Unhandled Promise Rejection: SyntaxError: JSON Parse error: Unrecognized token '<' "

**To Reproduce**
Steps to reproduce the behavior, such as the following:
1.  inspect in chrome
2. add a custom function
3. bind a button event with this function
4. click '</>按钮' button
5. See error on console panel

**Screenshots**
![image](https://user-images.githubusercontent.com/7335210/63223752-fb0ebb00-c1ec-11e9-8e6b-b432781d019c.png)

**Comment by Tinple** [comment]
Can you give us the url like `https://imgcook.taobao.org/edit?id=xxx`?

**Comment by rocketlyz** [comment]
> Can you give us the url like `https://imgcook.taobao.org/edit?id=xxx`?

 https://imgcook.taobao.org/edit?id=10525

**Comment by Ahkari** [comment]
Our DSL has not support event and scripts protocols yet.
We will fix this problem soon after.

**Comment by rocketlyz** [comment]
> Our DSL has not support event and scripts protocols yet.
> We will fix this problem soon after.

thx!
