### ISSUE TITLE
识别组件的能力会怎么实现呢？

### ISSUE THREAD

**Issue by zhangking** [taofed/imgcook#29]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by Tinple** [comment]
后续会通过深度学习图像识别的能力来实现
