### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by 7pou** [taofed/imgcook#31]
![image](https://user-images.githubusercontent.com/32350637/67058641-45c69800-f188-11e9-9dd1-33bed122c1b3.png)

Photoshop CC 2018 19.1.6

imgcook.pkg安装失败

**Comment by utkobe** [comment]
你好，能提供下具体失败的错误提示吗，如果是因为系统显示‘来自身份不明的开发者’，可以在 Mac 上，选取苹果菜单  -> 系统偏好设置 -> 点按“安全性与隐私”，然后点按“通用”。 然后解锁‘imgcook_photoshop_pkg’

**Comment by 7pou** [comment]
怎么找到安装日志的, 我发一下给你们


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruikun Cao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月18日(星期五) 上午9:35
收件人:&nbsp;"taofed/imgcook"<imgcook@noreply.github.com&gt;;
抄送:&nbsp;"赵一帆"<604264588@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taofed/imgcook] 安装失败 (#31)




你好，能提供下具体失败的错误提示吗，如果是因为系统显示‘来自身份不明的开发者’，可以在 Mac 上，选取苹果菜单  -&gt; 系统偏好设置 -&gt; 点按“安全性与隐私”，然后点按“通用”。 然后解锁‘imgcook_photoshop_pkg’

**Comment by 7pou** [comment]
安装步骤 :  介绍 - 许可 - 目的卷宗 - 安装类型 - 安装 - 摘要
在摘要这个步骤 提示 ,安装过程出错 , 安装失败 , 安装器遇到一个错误 , 导致安装失败 , 请联系软件生产企业以获得帮助。

**Comment by utkobe** [comment]
我们看一下

**Comment by Tinple** [comment]
Hi, 我们排查了下目前的安装器对新版的 Mac 系统确实不支持，我们后续会跟进这个问题。你可以先通过手动安装的方式来安装。具体步骤为：

1. 解压 imgcook.photoshop.zip  文件
2. 将 imgcook.photoshop 目录移到 Mac PS 的插件目录 `Mac OS: /Library/Application Support/Adobe/CEP/extensions/`
3. 重启 PS 查看是否有 imgcook 插件
