### ISSUE TITLE
github协同开发者没有邀请

### ISSUE THREAD

**Issue by cccisbug** [taofed/imgcook#32]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, such as the following:

**Expected behavior**
https://github.com/imgcook-dsl/half_flex2 这个仓库，新建dsl时填了协同管理员cccisbug，但没有协同邀请
**Screenshots**

*If you use sketch(Please complete the following information):*
 - PluginVersion: imgcook plugin version [e.g. 1.7.1]
 - sketchVersion: sketch version [e.g. 55.1]
 - sketchFile: problematic sketch file,compressed into zip

**Additional context**

**Comment by gindis** [comment]
需登录注册github账号的邮箱查收确认邀请。

**Comment by cccisbug** [comment]
> 需登录注册github账号的邮箱查收确认邀请。

谢谢您
