### ISSUE TITLE
VSCode 插件 bug

### ISSUE THREAD

**Issue by lukastong** [taofed/imgcook#33]
1. 快速设置中，未找到“编写函数”模块
2. 节点操作 => 事件绑定，绑定后导出代码，未找到绑定的事件

**Comment by gindis** [comment]
1. VSCode 里暂时还没支持编写函数功能
2. 这个问题我们看下，用的哪个 DSL 生成的代码

**Comment by lukastong** [comment]
@gindis 第二个问题指的也是在 VScode 插件里操作的问题，用的 react 那个

**Comment by gindis** [comment]
@lukastong 修复好了，重新点“生成模块”试下

**Comment by lukastong** [comment]
@gindis 好使了👍
