### ISSUE TITLE
photoshop 插件生成数据时，一直提示生成中

### ISSUE THREAD

**Issue by luoxianchao** [taofed/imgcook#35]
![image](https://user-images.githubusercontent.com/19643593/69535919-e85c0d00-0fb7-11ea-9a4e-40b341750dea.png)

**Comment by Tinple** [comment]
看下导出的时候 PS 里面是否有弹框出现 Block 了流程。另外如果官方提供的试验田文件导出正常的话可能是你使用的设计稿处理的问题，方便的话可以进官方群联系下管理员提供稿子，我们会帮忙排查下
