### ISSUE TITLE
这个项目会开源吗？

### ISSUE THREAD

**Issue by hxgqh** [taofed/imgcook#36]

**Comment by Tinple** [comment]
2020 年会有开源的计划

**Comment by shenshou** [comment]
能透露一下你们的更新计划吗 我看到官网更新日志最后一次更新实在6月份 快半年没更新了

**Comment by Tinple** [comment]
> 能透露一下你们的更新计划吗 我看到官网更新日志最后一次更新实在6月份 快半年没更新了

今年下半年都在内部做一些实验性的能力，对外部的感知可能不太多，下个月中旬我们会对外部做一次正式版的升级，会披露一些明年的计划和里程碑

**Comment by huliyou** [comment]
> 2020 年会有开源的计划

2021年咯

**Comment by gindis** [comment]
> > 2020 年会有开源的计划
> 
> 2021年咯

不好意思，目前还在打磨提升真实的还原的可用率。暂时还没完全开源的计划，未来数据和算法会通过 https://github.com/alibaba/pipcook 开源出来，欢迎关注。

**Comment by pengxiaobao** [comment]
> 2020 年会有开源的计划

2023年了

**Comment by LinWeiLong** [comment]
> > 2020 年会有开源的计划
> 
> 2023年了

2025了😁

**Comment by miaojing** [comment]
> > > 2020 年会有开源的计划
> > 
> > 
> > 2023年了
> 
> 2025了😁

https://github.com/alibaba/pipcook 目前只开源依赖的算法工程和部分数据，整个完全的项目确实一直没有开源计划，目前主要以服务淘天内部前端为主，内部还在基于大模型的能力升级，感谢关注
