### ISSUE TITLE
win装不了sketch ，能搞个类似axure win能用的吗？谢谢。用ps生成的不太准确。

### ISSUE THREAD

**Issue by HeZiCong** [taofed/imgcook#38]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by Tinple** [comment]
目前没有支持 axure 的计划，PS 还原效果确实没有 Sketch 精细，如果遇到 PS 生成不准确的问题可以进群提供给我们相关的 Case 我们可以帮忙跟进下

**Comment by HeZiCong** [comment]
那以后win除了ps就没其他工具了吗


在2019年12月06日 17:16，Tinple 写道：

目前没有支持 axure 的计划，PS 还原效果确实没有 Sketch 精细，如果遇到 PS 生成不准确的问题可以进群提供给我们相关的 Case 我们可以帮忙跟进下

**Comment by Tinple** [comment]
是的，明年可能会提供 PS 的文件上传解析服务来优化这块的效果，现在插件的形式对我们的输入还是太少了
