### ISSUE TITLE
生成代码没有包含方法、state

### ISSUE THREAD

**Issue by SophinQ** [taofed/imgcook#39]
![image](https://user-images.githubusercontent.com/24472329/70681695-2efb7800-1cd7-11ea-86b1-cf4eec4bad77.png)
如上图。

**Comment by Tinple** [comment]
目前只有 React D2C Schema 这个 DSL 支持这部分能力，你可以关注切换下，我把它设为推荐 DSL 了

![image](https://user-images.githubusercontent.com/5363119/70681866-e1333f80-1cd7-11ea-88b0-6ec1cb331f8d.png)

**Comment by SophinQ** [comment]
> 目前只有 React D2C Schema 这个 DSL 支持这部分能力，你可以关注切换下，我把它设为推荐 DSL 了
> 
> ![image](https://user-images.githubusercontent.com/5363119/70681866-e1333f80-1cd7-11ea-88b0-6ec1cb331f8d.png)

刷新就看到了，不过切了提示生成失败

**Comment by Tinple** [comment]
看了下，是 `constructor` 解析出错了~ 因为在 vm2 里访问不到这个属性，下周会修复这个问题，你可以先不要设置 `constructor` 或者可以在左下角源码里把 `constructor` 改为 `_constructor` 。后续我们会在实现的时候把这个属性键自动做下转换。

![image](https://user-images.githubusercontent.com/5363119/70682668-8a7b3500-1cda-11ea-9c33-a18f902b2f40.png)

**Comment by SophinQ** [comment]
> 看了下，是 `constructor` 解析出错了~ 因为在 vm2 里访问不到这个属性，下周会修复这个问题，你可以先不要设置 `constructor` 或者可以在左下角源码里把 `constructor` 改为 `_constructor` 。后续我们会在实现的时候把这个属性键自动做下转换。
> 
> ![image](https://user-images.githubusercontent.com/5363119/70682668-8a7b3500-1cda-11ea-9c33-a18f902b2f40.png)

好的，谢谢，删掉设置后，成功了。
