### ISSUE TITLE
vscode插件有时点击生成模块没有反应

### ISSUE THREAD

**Issue by Ciory** [taofed/imgcook#40]
imgcook vscode版本: v0.04
vscode :版本: 1.41.0
               提交: 9579eda04fdb3a9bba2750f15193e5fafe16b959
               日期: 2019-12-11T17:58:38.338Z
               Electron: 6.1.5
               Chrome: 76.0.3809.146
               Node.js: 12.4.0
               V8: 7.6.303.31-electron.0
               OS: Darwin x64 19.0.0
sketch 版本: 58

**Comment by gindis** [comment]
> imgcook vscode版本: v0.04
> vscode :版本: 1.41.0
> 提交: 9579eda04fdb3a9bba2750f15193e5fafe16b959
> 日期: 2019-12-11T17:58:38.338Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Darwin x64 19.0.0
> sketch 版本: 58

选择哪个 DSL 模版生成模块代码的
