### ISSUE TITLE
请问未来有增加针对React-Native代码生成的计划吗

### ISSUE THREAD

**Issue by penghuwan** [taofed/imgcook#41]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by gindis** [comment]
未来会有，目前没有资源投入开发，亲有兴趣开发贡献下吗 😄

**Comment by penghuwan** [comment]
是的，我们正在开发react-native的DSL，相关链接：https://github.com/imgcook-dsl/react-native-gf
imgcook是一个非常厉害的工具，感谢你们的奉献
