### ISSUE TITLE
请新开钉钉群，现在的钉钉群已经满人了

### ISSUE THREAD

**Issue by bigbirdhzp** [taofed/imgcook#43]
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

**Comment by gindis** [comment]
可以扫下面二维码进群：
![](https://gw.alicdn.com/tfs/TB1wITit.Y1gK0jSZFCXXcwqXXa-750-990.png)

**Comment by bigbirdhzp** [comment]
> 可以扫下面二维码进群：
> ![](https://camo.githubusercontent.com/ba0731b167413e1e10d13fbcec0b8fcaeb1e79ba/68747470733a2f2f67772e616c6963646e2e636f6d2f7466732f54423177495469742e5931674b306a535a464358586377715858612d3735302d3939302e706e67)

谢谢
