### ISSUE TITLE
应该给项目设置dsl会更好一些（而不是给团队设置dsl）

### ISSUE THREAD

**Issue by hxgqh** [taofed/imgcook#46]
Web界面中，只允许给团队设置一个dsl。但是实际上一个团队管理多个不同类型的前端项目，每个项目就需要使用不同的dsl。

**Comment by gindis** [comment]
> Web界面中，只允许给团队设置一个dsl。但是实际上一个团队管理多个不同类型的前端项目，每个项目就需要使用不同的dsl。

感谢反馈，原先支持项目设置  DSL 的，但调研发现一个团队前端使用多个技术栈较少，所以把项目维度配置 DSL 去掉了，我们重新评估下。

**Comment by hxgqh** [comment]
以uni-app为例，由于uni-app的页面和组件的模板不一样，所以只能由两个dsl生成。对于uni-app的技术团队，同一个技术栈也会存在问题。

**Comment by Tinple** [comment]
目前内部讨论了下暂时只定到团队这层做配置
