### ISSUE TITLE
sketch imgcook 插件一直停留在"正在初始化"，无法导出 JSON

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#47]
环境：
sketch 52.6
imgcook 插件 2.1.14
网络 移动4G/普通wifi

复现路径：
在官网下载 zip 包，使用其中试验田文件，选择任意内容导出，可复现

异常体现：
sketch imgcook 插件一直停留在"正在初始化"

**Comment by utkobe** [comment]
你好，麻烦检查一下是不是系统权限的问题，在 Mac 上，选取「系统偏好设置」- 「安全性与隐私」-「通用」，底部解锁 imgcook.framework。

**Comment by cheogo** [comment]
你好，我根据你和文档上的指引 https://www.imgcook.com/docs?slug=install-plugin

发现我的系统是 Mac Mojave，而不是  Mac os catalina

所以我的异常体现是，「安全性与隐私」-「通用」没有出现阻止信息。插件能安装，但是导出的时候一直提示 "正在初始化"

**Comment by cheogo** [comment]
目前  sketch 52.6、 imgcook 1.7.1、 macOS Mojave 10.14.6 是跑得通流程的。

如果我系统提升到 Mac catalina 再，升级 imgcook ^2.0 吧

**Comment by utkobe** [comment]
@cheogo 可以尝试一下不通过 sketch 插件面板，直接在 sketch 上面的菜单 =》 插件 =》 导出数据尝试一下，如果不行的话，我们看到您这边 sketch 的插件版本比我们测试的版本低，可以尝试一下升级 sketch

**Comment by wushiwein119** [comment]
@cheogo 目前需要升级你的sketch53以上，推荐54版本以上
