### ISSUE TITLE
imgcook 编辑页删除部分 dom 节点后导出代码失败

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#48]
环境：
sketch 52.6
imgcook 插件 1.7.1
网络 移动4G/普通wifi

复现路径：
成功导出 JSON -> copy 到编辑页 -> 成功渲染后 -> 保存导出 Vue 代码正常 -> 删除 dom 后再次导出 Vue 代码，提示失败

异常体现：
只有 Vue 会导出失败、其他类型代码可以导出

**Comment by gindis** [comment]
> 环境：
> sketch 52.6
> imgcook 插件 1.7.1
> 网络 移动4G/普通wifi
> 
> 复现路径：
> 成功导出 JSON -> copy 到编辑页 -> 成功渲染后 -> 保存导出 Vue 代码正常 -> 删除 dom 后再次导出 Vue 代码，提示失败
> 
> 异常体现：
> 只有 Vue 会导出失败、其他类型代码可以导出

提供下模块的 ID

**Comment by cheogo** [comment]
id: 24121

**Comment by gindis** [comment]
> id: 24121

修复好了，重新生成下。

**Comment by cheogo** [comment]
大佬牛批！
