### ISSUE TITLE
https://imgcook.taobao.org/editor 页，异常上报异常

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#49]
复现路径：

使用 https://imgcook.taobao.org/editor 页，处理页面/组件时，如果发生异常，异常信息不会正确上报

异常体现：

上报的地址 http://imgcook.taobao.org/error2 为 http 协议，而访问的页面是 https，api 上报会被浏览器安全策略拦截

推荐修复：

使用 img.src 上报或者统一 http(s)

**Comment by Tinple** [comment]
有更具体的描述例子吗？是说在编辑器里搭建编辑的时候出现 JS 错误的异常处理 or 调试？

**Comment by cheogo** [comment]
https://github.com/taofed/imgcook/issues/48

之前出现上面这个问题的时候，我看了下 chrome 调试工具，应该是接口响应异常了。

对于这个异常，你们上报异常的请求  http://imgcook.taobao.org/error2 也是异常的

**Comment by Tinple** [comment]
这是一个统一的异常处理，不影响单个接口异常，后续我们会优化单个接口异常的错误处理
