### ISSUE TITLE
生成 Vue 代码异常

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#51]
复现：修改组件类名后，导出的 Vue 代码，存在异常如： <div class="line" / v-if="true" >

ID: 24559

**Comment by gindis** [comment]
![image](https://user-images.githubusercontent.com/758046/76729818-fa470300-6794-11ea-92aa-176b5e09b6f8.png)
请问怎么改的组件类名，看了下 ID: 24559 导出 Vue 代码没问题的

**Comment by cheogo** [comment]
@gindis 不好意思，刚刚一直在开会。

在 Vue 中 <div class="line" / v-if="true"> 是会有异常的。
正确的应该是 <div class="line" v-if="true"  />

不同的地方在于 "/" 的位置

**Comment by cheogo** [comment]
我导出的代码，和你导出的代码是一样的。

但是你 copy 到项目中运行就会发现问题了。

![image](https://user-images.githubusercontent.com/18629842/76741689-ec03e180-67aa-11ea-9506-90c123ed66f4.png)

**Comment by gindis** [comment]
Fixed，重新生成试下

**Comment by cheogo** [comment]
手动点赞
