### ISSUE TITLE
希望能通过 “应用设置” 的 viewport 和 width，控制 css 输出的 px 值

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#52]
如下图，在设计尺寸为 750px， viewport 375px 的情况下。期望输出的图片宽度为 630px/2 = 315px

![image](https://user-images.githubusercontent.com/18629842/76817359-91679580-683d-11ea-9700-5f93d729b1a4.png)

如果在，在设计尺寸为 750px， viewport 750px 的情况下。输出的图片宽度才为 630px

------

移动端适配适配除了 flex、vw、rem 等方案，还有 meta viewport 的方案。该方案通过指定 viewport 的 device-width 来设置移动端的画布大小。目前项目中用的是 375px 为满屏宽度，而输出的 css 为 630px，会溢出屏幕。

**总的来说，希望提供一种方式来控制整体 css px 输出的值，上面说的是建议，具体可另外实现。**

**Comment by cheogo** [comment]
![image](https://user-images.githubusercontent.com/18629842/76818097-a80eec00-683f-11ea-9048-31aaf57ad19b.png)

ID: 24604

**Comment by Tinple** [comment]
你描述的设计尺寸 `viewport 750px` 对应的应该就是这份配置里的 `width: 750`，使用 meta viewport 方案应该也可以在 DSL 输出中完成这部分的转换（参考 rem 等）。

目前网页上的 Mobile 预览模式确实还不能自适应，我们会尽快修复这个问题！

**Comment by cheogo** [comment]
有一种思路是通过 plugin 来控制，css 的输出比例

**Comment by Tinple** [comment]
原问题可以通过『编辑器 - 应用设置』解决
