### ISSUE TITLE
官方插件提示图片上传错误

### ISSUE THREAD

**Issue by JohnieXu** [taofed/imgcook#54]
**Describe the bug**
在mac环境下，使用Photoshop CC 2018，最新版本官方imgCook插件，导出官方提供的实例psd文件提示图片上传错误

**Expected behavior**
导出的图片上传正常

**Screenshots**
![](https://tva1.sinaimg.cn/large/00831rSTly1gcx4euzvvaj30p00oggm4.jpg)

错误如下：
```
图片上传错误：{"errno":-2,"code":"ENOENT","syscall":"open","path":"/private/var/folders/k3/f2ym5y051nl2dy0yxyt4ylsc0000gn/T/TemporaryItems/宝贝3124.png"}
```

**Comment by Tinple** [comment]
是因为临时图片存储地址找不到的原因，
能帮忙确认下，本机这个地址是否有这张图片呢？

**Comment by JohnieXu** [comment]
> 是因为临时图片存储地址找不到的原因，
> 能帮忙确认下，本机这个地址是否有这张图片呢？

确认过临时文件的位置确实不存在此图片

**Comment by Tinple** [comment]
Mac 临时环境问题，用户使用已正常，closed
