### ISSUE TITLE
schema 解析异常

### ISSUE THREAD

**Issue by cheogo** [taofed/imgcook#55]
#### 问题
schema 在 imgcook 编辑器上解析异常  [schema.txt](https://github.com/taofed/imgcook/files/4386349/schema.txt)
> schema json 能被正常格式化 https://www.json.cn/

#### 复现
在 https://imgcook.taobao.org/editor#/? 粘贴 [schema.txt](https://github.com/taofed/imgcook/files/4386349/schema.txt)

#### 环境
如果需要 sketch 文件，可以提供，插件版本 1.7

**Comment by cheogo** [comment]
![image](https://user-images.githubusercontent.com/18629842/77634061-57a83480-6f8b-11ea-98fb-296538283861.png)

**Comment by Tinple** [comment]
1.7.1 这个版本太老了，可以更新到最新的试一试，最新插件版本 2.2.0

**Comment by cheogo** [comment]
好的，解决了。我以后更新到最新版，确定后再来提问。
