### ISSUE TITLE
关于flutter的代码设计支持希望

### ISSUE THREAD

**Issue by MoeGuoH** [taofed/imgcook#57]
现在flutter app框架较为流行，感觉imgcook这一套框架完全可以自动生成对应的界面代码.

**Comment by miaojing** [comment]
你可以在https://www.imgcook.com/dsl 自定义DSL->精选下找到Flutter的DSL ，目前已经有用户贡献了此DSL，可以直接生成flutter的代码，点击关注此 dsl 即可使用

**Comment by MoeGuoH** [comment]
> D

了解了，谢谢~
