### ISSUE TITLE
看了下图层都是可见的，但是导出数据时显示图层不可见

### ISSUE THREAD

**Issue by 1Crazy** [taofed/imgcook#58]
Describe the bug
在mac环境下，使用Photoshop CC 2019，最新版本官方imgCook插件,出现如下报错

![](https://user-images.githubusercontent.com/24940058/79061922-c09be600-7cc7-11ea-9c56-a89185e4d61a.png)

**Comment by Tinple** [comment]
插件导出只能选中一个 `容器图层组` 进行导出，暂时不支持单图层的多选导出，比如 `组3` 即为一个`容器图层组

**Comment by 1Crazy** [comment]
哦哦
