### ISSUE TITLE
dsl更新模版，报“抱歉，网络异常，请稍后重试”

### ISSUE THREAD

**Issue by zhangking** [taofed/imgcook#59]
dsl 名字为 React Tuya

**Comment by gindis** [comment]
加个权限看下，id：gindis，可能是 github 接口调用失败

**Comment by zhangking** [comment]
给你加了 帮忙看下 谢谢

**Comment by gindis** [comment]
改好了，再试下
Server 端对  src 文件夹的 template.xtpl 有个强校验不能删掉，会优化下

**Comment by zhangking** [comment]
ok 你们这个 prettier 能不能升级下 有点来 没集成 babel-ts

**Comment by gindis** [comment]
OK，Prettier 的升级 我跟进下

**Comment by zhangking** [comment]
请问进展如何？

**Comment by gindis** [comment]
升级好了在测试，预计这两天会发发布

**Comment by gindis** [comment]
试下看，升级了
