### ISSUE TITLE
error: 发生了常规 Photoshop 错误。2019CC

### ISSUE THREAD

**Issue by moonssmile97** [taofed/imgcook#60]
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令"选择"当前不可用。

**Comment by LoveEocding** [comment]
error: 发生了常规 Photoshop 错误。该功能可能无法在这个版本的 Photoshop 中使用。 - 命令"选择"当前不可用。我也是这个问题 怎么修复的吗

**Comment by zyzweb** [comment]
有解决的吗?

**Comment by gindis** [comment]
> 有解决的吗?

解决了，请问您这边遇到什么问题？
