### ISSUE TITLE
是否能开放一种sketch命名约定，来对应组件类型？

### ISSUE THREAD

**Issue by zhangking** [taofed/imgcook#61]
比如通过skecth内某些group的命名 (如Select) 来定义一个组件, 然后识别后投传到在schema的componentName，方便自定义dsl转化代码，这种方式是否能暂时解决一部风问题。因为深度学习需要训练，且要各个团队训练自己的组件库识别可能有一定成本。

**Comment by gindis** [comment]
已支持在 sketch 标注生成 schema 里的 componentName，参考文档：https://www.imgcook.com/docs?slug=advanced-rules#vvQci

**Comment by zhangking** [comment]
我在编组添加了 #component:button# 但是在导出的schema查看并没有起作用。
我看文档需要 “组件需要在 imgcook 团队设置组件管理处（暂不支持）注册过”, 这个功能是暂时不可用么
