### ISSUE TITLE
上传图片到自己的cdn中

### ISSUE THREAD

**Issue by SilentFlute** [taofed/imgcook#64]
这不是一个bug，是一个咨询帖吧，所以没有按issue的格式来，见谅！
# 需求简述
我是一个前端开发人员，我司最近在尝试图片大厨，然后有一个需求：希望能将图片传到自己的cdn，就是最终希望在vs code中导出的代码里看到的图片的地址不是阿里云的地址，而是我们自己的cdn图片地址！
# 探索过程
翻阅了issue，查看了 #11 和 #54 ，以及团队设置>插件设置位置：
`选择初始化项目 Plugin：设置从模板生成新项目的 Plugin，目前只支持 VSCode imgcook studio 插件里生成代码使用`
`选择导出模块处理 Plugin：设置导出模块处理的 Plugin，目前只支持 VSCode imgcook studio 插件里生成代码使用`
以及文档中视觉稿一键还原>先导出数据再创建模块：
`等待一段时间后弹出如下提示框，此时粘贴板上已经有了插件导出的描述 Sketch 稿的 JSON 结构的数据，您可以直接点击 「去粘贴」按钮前往 imgcook 粘贴。`
得出了一个结论，也许不对，希望能得到你们的帮助：
# 结论
团队插件设置界面说`目前只支持 VSCode imgcook studio 插件里生成代码使用`，而我在vs code中点导出，导出代码到编辑器中看到的图片地址就已经是阿里云的了，而54 issue说自己用ps时遇到图片上传报错的问题，同时11 issue想自定义阿里云oss，而被回复说目前暂不支持，因此我推断：上传设计稿中的图片到自己的cdn这个动作应该在设计师从sketch/ps中粘贴json到图片大厨的过程中完成，而目前暂时不支持上传图片到自己cdn中！关于这个需求的处理过程，以及这个需求的结论是这样的吗？

**Comment by gindis** [comment]
参考下这个文档：https://www.imgcook.com/docs?slug=custom-imageupload-api

**Comment by SilentFlute** [comment]
@gindis 哦哦，感谢，只看到文档里的自定义plugin，没留意到它下面就是自定义图片上传接口相关的内容！另外就是创建这个插件的时候需要填写插件仓库，就是需要把示例代码类似`https://github.com/gindis/multipart-file-mode-showcase`这样上传图片到自己cdn的代码仓库的地址填上去是吧？也就是最后在imgcook-plugin目录中创建上传的仓库：`https://github.com/imgcook-plugin/上传图片.git`，那这样的话里面一些获取上传token accessKey之类的代码就暴露了不是，这样不就有安全隐患了嘛

**Comment by gindis** [comment]
考虑到用户上传 CDN 图床接口安全问题，上传接口配置在本地的（如下图），上传 Token accessKey 等信息不会暴露在 Plugin 代码中。

![image](https://user-images.githubusercontent.com/758046/80441336-5462e880-893d-11ea-87a8-bafbe41d56d7.png)

**Comment by SilentFlute** [comment]
@gindis 哦哦，这样啊，那如果这些token需要调接口，通过接口返回怎么办呢？以及这个.imgcookrc这个配置文件是如何使用的，都有哪些配置项可配以及作用是怎样的呢？我在文档中找了下似乎没找到

**Comment by SilentFlute** [comment]
@gindis .imgcookrc的文档找到了：`https://www.imgcook.com/docs?slug=cli`

**Comment by SilentFlute** [comment]
@gindis 你好，我暂时先把token需要调接口获取放了放，因为uploadUrl后面的查询字符串似乎就是一种token，但不排除我司(新单位)会用比如form data的形式传递token，想先走一遍流程，就是用上传图片的示例代码：`https://github.com/gindis/multipart-file-mode-showcase`来试了一下，参照[自定义图片上传接口](https://www.imgcook.com/docs?slug=custom-imageupload-api)来操作的，但是结果并没有是`src={'http://127.0.0.1:7001/public/aaa.png'}`这种形式，只是图片被生成到了`images`文件夹中(一开始我没有用`.imgcookrc`配置文件，也没用插件，因此图片地址直接是阿里云的地址且没有一个images文件夹)，同时是`src={'./images/aaa.png'}`这种形式，而上传图片的示例代码已经在本地运行了，也能上传图片到`public`目录下，`imgcook config set`的配置也是按文档来的：
```
{
  "accessId": "xxx",
  "dslId": "41",
  "generator": [
    "@imgcook/generator-react"
  ],
  "plugin": [
    "@imgcook/plugin-images",
    "@imgcook/plugin-generate"
  ],
  "uploadUrl": "http://127.0.0.1:7001/ajax?_csrf=BnhxB6ra9RAH3hBxDeiJjLI8"
}
```
windows系统是创建在了c盘用户目录下，配置文件是创建成功了的，然后团队设置里面插件也设置的是`@imgcook/plugin-images`和`@imgcook/plugin-generate`，然后`imgcook config --set uploadUrl http://127.0.0.1:7001/ajax?_csrf=BnhxB6ra9RAH3hBxDeiJjLI8`之后就生成了上面的`.imgcookrc`文件，最后用vs code的imgcook插件导出代码，可是最后结果就成了我一开始描述那样，img的src并没有被换成预期的cdn的url，而依旧是老的相对路径，我暂时没找到是哪里出了问题，你能帮我看看吗？

**Comment by gindis** [comment]
运行 multipart-file-mode-showcase 项目的代码 测试上传图片成功的吗？如果测试成功会输出如下图结果

![image](https://user-images.githubusercontent.com/758046/80465959-70cb4900-896e-11ea-8086-cf5fdfd513f9.png)

**Comment by SilentFlute** [comment]
@gindis 是成功的，页面上的输出结果和你这个一样，只是我没有去指定图片的名称，然后那个url在浏览器中访问也是符合预期的返回了我上传的图片，所以我才说来向你咨询一下

**Comment by gindis** [comment]
@SilentFlute 
重启 vscode 再导出试下或在终端执行 `imgcook pull <moduleid>` 导出看下。如果还不可以，加个联系方式(钉钉)看下？

**Comment by gindis** [comment]
@SilentFlute 「一个测试模块」这个是你的模块吧，在日志查了下，发现这模块在个人空间下不在团队下，所以 vscode 工具导出不会调用插件处理。可以使用 imgcook pull <moduleid> 指令导出。

**Comment by SilentFlute** [comment]
@gindis 真是奇怪了，现在开机再试就又可以了，同样的操作，居然可以了！
然后我操作的模块一直都是团队下的，白天不行，刚又可以了！
以及说到这个「一个测试模块」，我之前刚接触你们的imgcook时创建项目各种创建不了，各种提示重名，然后无论怎么搞都重名，似乎也取过一个「一个测试模块」的名字，但是依旧是重名，而我的个人项目里又死活都看不到这些已经重名的项目，也是醉了，然后模块倒是好创建，主要是项目，个人项目，怎么搞都是重名，我最后不得不用自己的昵称建了一个个人项目

**Comment by SilentFlute** [comment]
@gindis 然后我突然想到：要是`.imgcook`目录就在项目目录里就好了，这样直接提交到仓库中，其他人使用也方便多了，然后我把c盘用户目录下的`.imgcook`目录剪切到了项目根目录，导出之后图片能正常上传，一切正常，但是c盘下还是会自动生成一个`.imgcook`目录，并且会装上`@imgcook/plugin-images`和`@imgcook/plugin-generate`插件，但没有生成`.imgcookrc`文件，因此最后导出的代码也不知道是用的哪一个配置文件；
另一个问题，还是上传token的问题：
1. 有可能是获取上传token，然后将文件给服务端传，然后服务端返回给我url(就像现在这个流程一样)
2. 也有可能是获取token之后通过一些第三方例如七牛云，百度云等的js-sdk去直接传，然后那边给我返回upload key，我自己拼接url，或者返回给我完整的url
无论哪种，都需要token，而此时token如何配置呢？用nodejs去修改c盘下的`.imgcookrc`文件？那如果token是通过非查询字符串的方式传递呢？又或者直接通过第三方云服务的js-sdk上传呢？

**Comment by gindis** [comment]
@SilentFlute 通过自定义插件的方式来实现读取项目下自己定义的配置文件，这样也可以解决 token 的配置问题。
自定义插件文档：https://www.imgcook.com/docs?slug=plugin

**Comment by SilentFlute** [comment]
@gindis 关于配置文件`.imgcookrc`，它似乎只能存在用户目录而不是项目目录下，我刚复制内容之后在项目目录创建了`.imgcookrc`和`/.imgcook/.imgcookrc`，然后删除了用户目录下的这个配置文件/文件夹，接着导出的时候它还是会自动创建用户目录下的配置文件并安装相应的依赖，这样的话似乎通过插件来读取配置文件并修改上传url后面的查询字符串就不太现实了，毕竟我的用户名是aaa，其他人可能是bbb，而且如果token是通过非查询字符串的方式传入和使用第三方的上传js-sdk的话我理解就比较复杂了：
1. 需要写一个中间层的服务，上传url填这个中间层，然后中间层再去获取token来调真实的上传接口上传文件，最后返回imgcook需要的内容→文件让服务端来传
2. 而第三方上传js-sdk我理解是不是也需要中间层搭在imgcook和js-sdk之间，js-sdk传完返回了，中间层再返回imgcook它需要的内容→前端直接传

综合起来看：一来配置文件不好定位，二来实现起来比较啰嗦，其中坑会比较多同时价值貌似不是太大，相比开发成本来说收益不是太大，毕竟这也可以通过普通的上传图片到cdn的方式进行，而且上面提到的这个中间层的代码需要放到imgcook的github上对吧，那获取token相关的东西不就暴露了嘛？
不知道这些我理解的对不对

**Comment by gindis** [comment]
@SilentFlute 不是将 .imgcookrc 移到项目下哈，意思是说可以单独定义一个 plugin 去实现，使用 imgcook vscode 插件导出时调用 Plugin 的同时会将工作空间目录 workspaceFolders 和 导出指定目录以参数形式传给 Plugin，因此你只要配合自己开发的 plugin 定义一个配置文件(用来存token、uploadUrl等)放在项目目录下读取就好了，隐私信息放在自己定义的本地配置文件就不会暴露了。

自定义 Plugin 开发文档：https://www.imgcook.com/docs?slug=plugin
参考示例：https://github.com/imgcook-plugin/plugin-directory-rax/blob/master/src/index.js#L127

Plugin 
```
/**
 * @name plugin example
 * @param {Object} option: { data, filePath, config, workspaceFolders }
 * - {Object} data: imgcook module code data
 * - {String} filePath: file storage directory
 * - {Object} config: cli config
 * - {Array} workspaceFolders: workspace folder，called in the vscode plugin
 */

const pluginHandler = async options => {
  let { data } = options;
  // body...
  return data;
};

module.exports = (...args) => {
  return pluginHandler(...args).catch(err => {
    console.log(err);
  });
};
```

**Comment by SilentFlute** [comment]
@gindis 哈哈哈，好嘛，这样啊，我还以为是将`.imgcookrc`移动到项目目录下呢，尴尬了><|||
抱歉我还有两个问题哈：
1. 项目中有个配置文件来存放token uploadUrl这些，导出的时候调用插件，然后插件读取该文件获得token uploadUrl这些信息，那这些信息要如何生效呢？是不是依旧要写到c盘用户目录的`.imgcookrc`中？这样的话是不是可以把c盘的用户名也写到本地配置文件中以供插件读取呢？
2. 如果遇到获取token需要调用接口的情况，上传token需要接口返回，那此时是不是就是获取token的接口需要放到本地配置文件中，导出的时候，调用插件，插件读本地配置文件获取到token接口然后调token接口，获得token之后我就有点懵了，如果要修改c盘用户下的`.imgcookrc`文件的`uploadUrl`而token又不是以查询字符串的形式拼接在`uploadUrl`后面那怎么搞呢？比如让后端修改上传接口，token直接以查询字符串的形式跟在上传的url后面？

**Comment by gindis** [comment]
@SilentFlute 
1. Plugin 内读取配置文件实时生效的没有 Cache，而读取通用配置 .imgcookrc 有加 Cache 的，如果修改了需要重启 vscode。
2. 官方给的示例解决方案 uploadUrl 鉴权只能拼接在 URL 上。如果要扩展需要自定义类似 @imgcook/plugin-images Plugin 实现。

**Comment by SilentFlute** [comment]
@gindis 哦，原来读取那个c盘下的配置文件有延迟，我说怎么昨天我修改了uploadUrl之后怎么试都不行，关机下班，回去打开再试就ok了！
1. 我不是太明白，比如上传的uploadUrl，这个要设置在哪里从而让imgcook vs code插件能将图片上传到uploadUrl呢？难道不是c盘的用户里面那个`.imgcookrc`里？如果不是的话该怎么搞呢？
2. 带着第一个问题，我去看了下@imgcook/plugin-images的代码：[https://github.com/imgcook-plugin/plugin-images/blob/master/lib/upload.js#L42](https://github.com/imgcook-plugin/plugin-images/blob/master/lib/upload.js#L42)，这里看到了uploadUrl，然后最后在这里[https://github.com/imgcook-plugin/plugin-images/blob/master/index.js#L79](https://github.com/imgcook-plugin/plugin-images/blob/master/index.js#L79)发现uploadUrl最后还是cli config里面的配置嘛，就还是c盘下那个通用配置`.imgcookrc`嘛，所以似乎还是要先解决第一个问题，然后才好往下进行(手动捂脸.jpg)

**Comment by SilentFlute** [comment]
最后没有采取直接将图片上传到自己的cdn中的方式，因为图片不多，就直接放到应用服务器即可，只是开发了一个dsl：[img-module](https://github.com/imgcook-dsl/img-module)，来将img的src引用相对路径的形式改为了模块化引用的形式：
```
<img src='./images/xxx.png' />
```
改为了：
```
import img0 from './images/xxx.png';
<img src={img0} />
```
友情提示：如果需要将图片导出到images文件夹中，那么需要使用导出模块处理插件：`@imgcook/plugin-images`和`@imgcook/plugin-generate`，不然默认img的src是一个私有的阿里云的地址，而且图片不会被导出到images文件夹中！
如果需要在导出时上传图片到自己的cdn中，则需要直接在项目中定义一个配置文件，然后通过插件的`workspaceFolders`读取这个配置文件使用，不再使用全局的`/.imgcook/.imgcookrc`配置文件，当然了，这个插件需要自己编写！
这个问题就暂时关闭了，如有小伙伴遇到此需求并做了更深入的探索，希望能不吝分享：）
同时，如果我司后面的业务中需要实现该功能，我也会到这和大家~求助~分享
