### ISSUE TITLE
生成的小程序代码布局错乱

### ISSUE THREAD

**Issue by ZYH0320** [taofed/imgcook#66]

**Comment by utkobe** [comment]
你好，模块地址可以提供一下吗

**Comment by ZYH0320** [comment]
https://www.imgcook.com/editor#/?id=30811&action=selectModule

**Comment by ZYH0320** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruikun Cao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 中午11:23
收件人:&nbsp;"taofed/imgcook"<imgcook@noreply.github.com&gt;;
抄送:&nbsp;"张育浩"<770528727@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taofed/imgcook] 生成的小程序代码布局错乱 (#66)





 
你好，模块地址可以提供一下吗

**Comment by utkobe** [comment]
用的哪个 dsl， 看一下是否是样式引入的问题～
