### ISSUE TITLE
登陆失败了。

### ISSUE THREAD

**Issue by wgqzlj** [taofed/imgcook#70]
抱歉，服务器出错了
服务器出错了，请重新刷新页面或返回首页

另外，底部钉钉群二维码失效了。

**Comment by gindis** [comment]
> 抱歉，服务器出错了
> 服务器出错了，请重新刷新页面或返回首页
> 
> 另外，底部钉钉群二维码失效了。

多试两次看下，最近 github 接口不是很稳定

扫描下面钉钉群二维码
![image](https://user-images.githubusercontent.com/758046/84368688-78863a80-ac08-11ea-88ff-9211af2d34ce.png)
