### ISSUE TITLE
无法粘贴

### ISSUE THREAD

**Issue by huck-viem** [taofed/imgcook#71]
If you want to communicate with us further, please scan the qr code below:
![imgcook钉钉群二维码](https://ai-sample.oss-cn-hangzhou.aliyuncs.com/imgcook%E9%92%89%E9%92%89%E7%BE%A4%E4%BA%8C%E7%BB%B4%E7%A0%81.jpeg)

* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by gindis** [comment]
有什么异常提示吗
