### ISSUE TITLE
请教数据状态是用什么管理的

### ISSUE THREAD

**Issue by yeyuguo** [taofed/imgcook#72]
landing 数据状态是用 redux 管理， 但发现它会有很明显的卡顿现象！

而该平台的 imgcook 的使用体验非常流畅，想请教下，是用什么数据状态管理，做到如此流畅体验的？

**Comment by gindis** [comment]
> landing 数据状态是用 redux 管理， 但发现它会有很明显的卡顿现象！
> 
> 而该平台的 imgcook 的使用体验非常流畅，想请教下，是用什么数据状态管理，做到如此流畅体验的？

mobx，一个较轻量级的库。
https://mobx.js.org/README.html

**Comment by yeyuguo** [comment]
> > landing 数据状态是用 redux 管理， 但发现它会有很明显的卡顿现象！
> > 而该平台的 imgcook 的使用体验非常流畅，想请教下，是用什么数据状态管理，做到如此流畅体验的？
> 
> mobx，一个较轻量级的库。
> https://mobx.js.org/README.html

多谢大佬
