### ISSUE TITLE
添加 dsl time out 

### ISSUE THREAD

**Issue by jamieYou** [taofed/imgcook#73]
![image](https://user-images.githubusercontent.com/19544032/87895881-3b1f9300-ca79-11ea-80fd-6f01724b5346.png)

点创建之后，等待很长时间，然后提示 time out

创建后的代码仓库是空的，并且没有收到邀请邮件

我创建了4个仓库都不行
uni-app-dsl
uni-app-dsl2
uni-app-dsl3
[uni-app-view](https://github.com/imgcook-dsl/uni-app-view)

**Comment by gindis** [comment]
我们看下

**Comment by gindis** [comment]
> 点创建之后，等待很长时间，然后提示 time out
> 
> 创建后的代码仓库是空的，并且没有收到邀请邮件
> 

改好了，重新创建下。

**Comment by jamieYou** [comment]
@gindis https://github.com/imgcook-dsl/uni-app-vue/graphs/contributors
仓库创建成功，但我没有收到邀请消息

**Comment by gindis** [comment]
> @gindis https://github.com/imgcook-dsl/uni-app-vue/graphs/contributors
> 仓库创建成功，但我没有收到邀请消息

有发送邀请的，到你注册 GitHub 账号邮箱查看下，或者点击 https://github.com/imgcook-dsl/uni-app-vue/invitations

![image](https://user-images.githubusercontent.com/758046/87905494-4089d700-ca93-11ea-93a4-b02bd062c701.png)

**Comment by jamieYou** [comment]
@gindis 可以了，谢谢
